management:

  endpoints:
    web:
      exposure:
        include: "*"

  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

server:
  use-forward-headers: true